# This file was generated by GoReleaser. DO NOT EDIT.
cask "goreach" do
  name "goreach"
  desc "Find unreached code paths in running Go services."
  homepage "https://github.com/yag13s/goreach"
  version "0.10.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "goreach"

  on_macos do
    on_intel do
      url "https://github.com/yag13s/goreach/releases/download/v#{version}/goreach_#{version}_darwin_amd64.tar.gz"
      sha256 "7872e525136b0629b1d14ae857831167d2a14fc4ad9871e39bc7e09573ebc802"
    end
    on_arm do
      url "https://github.com/yag13s/goreach/releases/download/v#{version}/goreach_#{version}_darwin_arm64.tar.gz"
      sha256 "e6107e59b66749f8ffa81b8e66506cab6bff292c510f8bbfcf89c4b7e9608d51"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/yag13s/goreach/releases/download/v#{version}/goreach_#{version}_linux_amd64.tar.gz"
      sha256 "c4ef981a4c177272d4628c51734b5924d195089d0694d753517e8ae7ccce7d44"
    end
    on_arm do
      url "https://github.com/yag13s/goreach/releases/download/v#{version}/goreach_#{version}_linux_arm64.tar.gz"
      sha256 "d879ae2a11d0dde98cf59edb6475ff8f5ad831d436748a151b48d8301cec266f"
    end
  end

  # No zap stanza required
end
