# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Goreach < Formula
  desc "Find unreached code paths in running Go services."
  homepage "https://github.com/yag13s/goreach"
  version "0.10.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yag13s/goreach/releases/download/v0.10.2/goreach_0.10.2_darwin_amd64.tar.gz"
      sha256 "8aee3be0f925140e617df04b4d247adbf9ea24441e94d642fd33d53a772f9363"

      define_method(:install) do
        bin.install "goreach"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yag13s/goreach/releases/download/v0.10.2/goreach_0.10.2_darwin_arm64.tar.gz"
      sha256 "8070ef2da91fa29d5f47ffcbcc601ba0ae1804414400e9a703bad12f120681cc"

      define_method(:install) do
        bin.install "goreach"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yag13s/goreach/releases/download/v0.10.2/goreach_0.10.2_linux_amd64.tar.gz"
      sha256 "6d3b551c1a2f29def8edc2d497074bd4fdcebb702e076813c955d2b8241cefce"
      define_method(:install) do
        bin.install "goreach"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yag13s/goreach/releases/download/v0.10.2/goreach_0.10.2_linux_arm64.tar.gz"
      sha256 "f9ddee0d32e4744d3eca5922e2a1c04ca0d38ee9e980680d4c07e29eacf8d09d"
      define_method(:install) do
        bin.install "goreach"
      end
    end
  end

  test do
    system "#{bin}/goreach", "--help"
  end
end
